/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2024-12-19 00:21:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>코딩 전문가를 만들기 위한 온라인 강의 시스템</title>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>공지사항목록</title>\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"/css/customer/layout.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("        #visual .content-container{	\r\n");
      out.write("            height:inherit;\r\n");
      out.write("            display:flex; \r\n");
      out.write("            align-items: center;\r\n");
      out.write("            \r\n");
      out.write("            background: url(\"../../images/customer/visual.png\") no-repeat center;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- header 부분 -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("	<!-- --------------------------- <visual> --------------------------------------- -->\r\n");
      out.write("	<!-- visual 부분 -->\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"visual\">\r\n");
      out.write("		<div class=\"content-container\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- --------------------------- <body> --------------------------------------- -->\r\n");
      out.write("	<div id=\"body\">\r\n");
      out.write("		<div class=\"content-container clearfix\">\r\n");
      out.write("\r\n");
      out.write("			<!-- --------------------------- aside --------------------------------------- -->\r\n");
      out.write("			<!-- aside 부분 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<aside class=\"aside\">\r\n");
      out.write("				<h1>고객센터</h1>\r\n");
      out.write("\r\n");
      out.write("				<nav class=\"menu text-menu first margin-top\">\r\n");
      out.write("					<h1>고객센터메뉴</h1>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a class=\"current\"  href=\"/customer/notice\">공지사항</a></li>\r\n");
      out.write("						<li><a class=\"\"  href=\"/customer/faq\">자주하는 질문</a></li>\r\n");
      out.write("						<li><a class=\"\" href=\"/customer/question\">수강문의</a></li>\r\n");
      out.write("						<li><a class=\"\" href=\"/customer/event\">이벤트</a></li>\r\n");
      out.write("						\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"menu\">\r\n");
      out.write("		<h1>협력업체</h1>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a target=\"_blank\" href=\"http://www.notepubs.com\"><img src=\"/images/notepubs.png\" alt=\"노트펍스\" /></a></li>\r\n");
      out.write("			<li><a target=\"_blank\" href=\"http://www.namoolab.com\"><img src=\"/images/namoolab.png\" alt=\"나무랩연구소\" /></a></li>\r\n");
      out.write("						\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("					\r\n");
      out.write("			</aside>\r\n");
      out.write("			<!-- --------------------------- main --------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<main class=\"main\">\r\n");
      out.write("			<h2 class=\"main title\">공지사항</h2>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"breadcrumb\">\r\n");
      out.write("				<h3 class=\"hidden\">경로</h3>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>home</li>\r\n");
      out.write("					<li>고객센터</li>\r\n");
      out.write("					<li>공지사항</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"search-form margin-top first align-right\">\r\n");
      out.write("				<h3 class=\"hidden\">공지사항 검색폼</h3>\r\n");
      out.write("				<form class=\"table-form\">\r\n");
      out.write("					<fieldset>\r\n");
      out.write("						<legend class=\"hidden\">공지사항 검색 필드</legend>\r\n");
      out.write("						<label class=\"hidden\">검색분류</label>\r\n");
      out.write("						<select name=\"f\">\r\n");
      out.write("							<option  value=\"title\">제목</option>\r\n");
      out.write("							<option  value=\"writerId\">작성자</option>\r\n");
      out.write("						</select> \r\n");
      out.write("						<label class=\"hidden\">검색어</label>\r\n");
      out.write("						<input type=\"text\" name=\"q\" value=\"\"/>\r\n");
      out.write("						<input class=\"btn btn-search\" type=\"submit\" value=\"검색\" />\r\n");
      out.write("					</fieldset>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"notice margin-top\">\r\n");
      out.write("				<h3 class=\"hidden\">공지사항 목록</h3>\r\n");
      out.write("				<table class=\"table\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th class=\"w60\">번호</th>\r\n");
      out.write("							<th class=\"expand\">제목</th>\r\n");
      out.write("							<th class=\"w100\">작성자</th>\r\n");
      out.write("							<th class=\"w100\">작성일</th>\r\n");
      out.write("							<th class=\"w60\">조회수</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("							\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>8</td>\r\n");
      out.write("						<td class=\"title indent text-align-left\"><a href=\"detail\">스프링 8강까지의 예제 코드</a></td>\r\n");
      out.write("						<td>newlec</td>\r\n");
      out.write("						<td>\r\n");
      out.write("							2019-08-18		\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>146</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("							\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>7</td>\r\n");
      out.write("						<td class=\"title indent text-align-left\"><a href=\"detail.html\">스프링 DI 예제 코드</a></td>\r\n");
      out.write("						<td>newlec</td>\r\n");
      out.write("						<td>\r\n");
      out.write("							2019-08-15		\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>131</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("							\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>6</td>\r\n");
      out.write("						<td class=\"title indent text-align-left\"><a href=\"detail.html\">뉴렉쌤 9월 초 국기과정 모집 안내</a></td>\r\n");
      out.write("						<td>newlec</td>\r\n");
      out.write("						<td>\r\n");
      out.write("							2019-06-11		\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>517</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("							\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>5</td>\r\n");
      out.write("						<td class=\"title indent text-align-left\"><a href=\"detail.html\">뉴렉처 강의 수강 방식 안내</a></td>\r\n");
      out.write("						<td>newlec</td>\r\n");
      out.write("						<td>\r\n");
      out.write("							2019-05-24		\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>448</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("							\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>4</td>\r\n");
      out.write("						<td class=\"title indent text-align-left\"><a href=\"detail.html\">자바 구조적인 프로그래밍 강의 예제 파일</a></td>\r\n");
      out.write("						<td>newlec</td>\r\n");
      out.write("						<td>\r\n");
      out.write("							2019-04-24		\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>520</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"indexer margin-top align-right\">\r\n");
      out.write("				<h3 class=\"hidden\">현재 페이지</h3>\r\n");
      out.write("				<div><span class=\"text-orange text-strong\">1</span> / 1 pages</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"margin-top align-center pager\">	\r\n");
      out.write("		\r\n");
      out.write("	<div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<span class=\"btn btn-prev\" onclick=\"alert('이전 페이지가 없습니다.');\">이전</span>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	<ul class=\"-list- center\">\r\n");
      out.write("		<li><a class=\"-text- orange bold\" href=\"?p=1&t=&q=\" >1</a></li>\r\n");
      out.write("				\r\n");
      out.write("	</ul>\r\n");
      out.write("	<div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("			<span class=\"btn btn-next\" onclick=\"alert('다음 페이지가 없습니다.');\">다음</span>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("			</div>\r\n");
      out.write("		</main>\r\n");
      out.write("		\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ------------------- <footer> --------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </body>\r\n");
      out.write("    \r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
